use lib qw(./t/lib);
use Test::More tests => 12 * (60 + 22 + 64) + 3;

use Test::WebService::CPANTesters::Dependency;
use WebService::CPANTesters::Dependency;

Test::WebService::CPANTesters::Dependency->init;

{
    my ($module, $perl, $os) = ('Catalyst::Runtime', '5.10.0', 'any OS');
    Test::WebService::CPANTesters::Dependency->set_module($module);

    diag("module: " . $module);

    my $dep = WebService::CPANTesters::Dependency->new(+{
        perl => $perl,
        os => $os
    });
    $dep->find($module);
    my @deps = $dep->list();

    cmp_ok(@deps, '==', 60, 'number of dependency modules');

    is($deps[0]->module, 'Scalar::Util', 'module is Scalar::Util');
    is($deps[0]->depth, 1, 'depth is 1');
    is($deps[0]->warning, '', 'warning is empty');
    is($deps[0]->text_result, 'Core module', 'textresult is Core module');
    is($deps[0]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[0]->total_results, 0, 'totalresults is 0');
    is($deps[0]->passes, '', 'passes is empty');
    is($deps[0]->fails, '', 'fails is empty');
    is($deps[0]->unknowns, '', 'unknowns is empty');
    is($deps[0]->nas, '', 'nas is empty');
    is($deps[0]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[0]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[1]->module, 'Class::MOP', 'module is Class::MOP');
    is($deps[1]->depth, 1, 'depth is 1');
    is($deps[1]->warning, '', 'warning is empty');
    is($deps[1]->text_result, '', 'textresult is empty');
    is($deps[1]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[1]->total_results, 69, 'totalresults is 69');
    is($deps[1]->passes, 67, 'passes is 67');
    is($deps[1]->fails, 0, 'fails is 0');
    is($deps[1]->unknowns, 2, 'unknowns is 2');
    is($deps[1]->nas, 0, 'nas is 0');
    is($deps[1]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[1]->dependencies}, '==', 7, 'number of dependency modules');

    is($deps[2]->module, 'Test::Exception', 'module is Test::Exception');
    is($deps[2]->depth, 2, 'depth is 2');
    is($deps[2]->warning, '', 'warning is empty');
    is($deps[2]->text_result, '', 'textresult is empty');
    is($deps[2]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[2]->total_results, 385, 'totalresults is 385');
    is($deps[2]->passes, 384, 'passes is 384');
    is($deps[2]->fails, 1, 'fails is 1');
    is($deps[2]->unknowns, 0, 'unknowns is 0');
    is($deps[2]->nas, 0, 'nas is 0');
    is($deps[2]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[2]->dependencies}, '==', 3, 'number of dependency modules');

    is($deps[3]->module, 'Test::Harness', 'module is Test::Harness');
    is($deps[3]->depth, 3, 'depth is 3');
    is($deps[3]->warning, '', 'warning is empty');
    is($deps[3]->text_result, 'Core module', 'textresult is Core module');
    is($deps[3]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[3]->total_results, 0, 'totalresults is 0');
    is($deps[3]->passes, '', 'passes is empty');
    is($deps[3]->fails, '', 'fails is empty');
    is($deps[3]->unknowns, '', 'unknowns is empty');
    is($deps[3]->nas, '', 'nas is empty');
    is($deps[3]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[3]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[4]->module, 'Test::More', 'module is Test::More');
    is($deps[4]->depth, 3, 'depth is 3');
    is($deps[4]->warning, '', 'warning is empty');
    is($deps[4]->text_result, 'Core module', 'textresult is Core module');
    is($deps[4]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[4]->total_results, 0, 'totalresults is 0');
    is($deps[4]->passes, '', 'passes is empty');
    is($deps[4]->fails, '', 'fails is empty');
    is($deps[4]->unknowns, '', 'unknowns is empty');
    is($deps[4]->nas, '', 'nas is empty');
    is($deps[4]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[4]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[5]->module, 'Sub::Uplevel', 'module is Sub::Uplevel');
    is($deps[5]->depth, 3, 'depth is 3');
    is($deps[5]->warning, '', 'warning is empty');
    is($deps[5]->text_result, '', 'textresult is empty');
    is($deps[5]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[5]->total_results, 323, 'totalresults is 323');
    is($deps[5]->passes, 323, 'passes is 323');
    is($deps[5]->fails, 0, 'fails is 0');
    is($deps[5]->unknowns, 0, 'unknowns is 0');
    is($deps[5]->nas, 0, 'nas is 0');
    is($deps[5]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[5]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[6]->module, 'Carp', 'module is Carp');
    is($deps[6]->depth, 4, 'depth is 4');
    is($deps[6]->warning, '', 'warning is empty');
    is($deps[6]->text_result, 'Core module', 'textresult is Core module');
    is($deps[6]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[6]->total_results, 0, 'totalresults is 0');
    is($deps[6]->passes, '', 'passes is empty');
    is($deps[6]->fails, '', 'fails is empty');
    is($deps[6]->unknowns, '', 'unknowns is empty');
    is($deps[6]->nas, '', 'nas is empty');
    is($deps[6]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[6]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[7]->module, 'ExtUtils::MakeMaker', 'module is ExtUtils::MakeMaker');
    is($deps[7]->depth, 2, 'depth is 2');
    is($deps[7]->warning, '', 'warning is empty');
    is($deps[7]->text_result, 'Core module', 'textresult is Core module');
    is($deps[7]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[7]->total_results, 0, 'totalresults is 0');
    is($deps[7]->passes, '', 'passes is empty');
    is($deps[7]->fails, '', 'fails is empty');
    is($deps[7]->unknowns, '', 'unknowns is empty');
    is($deps[7]->nas, '', 'nas is empty');
    is($deps[7]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[7]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[8]->module, 'File::Spec', 'module is File::Spec');
    is($deps[8]->depth, 2, 'depth is 2');
    is($deps[8]->warning, '', 'warning is empty');
    is($deps[8]->text_result, 'Core module', 'textresult is Core module');
    is($deps[8]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[8]->total_results, 0, 'totalresults is 0');
    is($deps[8]->passes, '', 'passes is empty');
    is($deps[8]->fails, '', 'fails is empty');
    is($deps[8]->unknowns, '', 'unknowns is empty');
    is($deps[8]->nas, '', 'nas is empty');
    is($deps[8]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[8]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[9]->module, 'Sub::Name', 'module is Sub::Name');
    is($deps[9]->depth, 2, 'depth is 2');
    is($deps[9]->warning, '', 'warning is empty');
    is($deps[9]->text_result, '', 'textresult is empty');
    is($deps[9]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[9]->total_results, 309, 'totalresults is 309');
    is($deps[9]->passes, 309, 'passes is 309');
    is($deps[9]->fails, 0, 'fails is 0');
    is($deps[9]->unknowns, 0, 'unknowns is 0');
    is($deps[9]->nas, 0, 'nas is 0');
    is($deps[9]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[9]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[10]->module, 'Devel::GlobalDestruction', 'module is Devel::GlobalDestruction');
    is($deps[10]->depth, 2, 'depth is 2');
    is($deps[10]->warning, '', 'warning is empty');
    is($deps[10]->text_result, '', 'textresult is empty');
    is($deps[10]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[10]->total_results, 301, 'totalresults is 301');
    is($deps[10]->passes, 299, 'passes is 299');
    is($deps[10]->fails, 1, 'fails is 1');
    is($deps[10]->unknowns, 0, 'unknowns is 0');
    is($deps[10]->nas, 1, 'nas is 1');
    is($deps[10]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[10]->dependencies}, '==', 2, 'number of dependency modules');

    is($deps[11]->module, 'Scope::Guard', 'module is Scope::Guard');
    is($deps[11]->depth, 3, 'depth is 3');
    is($deps[11]->warning, '', 'warning is empty');
    is($deps[11]->text_result, '', 'textresult is empty');
    is($deps[11]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[11]->total_results, 390, 'totalresults is 390');
    is($deps[11]->passes, 390, 'passes is 390');
    is($deps[11]->fails, 0, 'fails is 0');
    is($deps[11]->unknowns, 0, 'unknowns is 0');
    is($deps[11]->nas, 0, 'nas is 0');
    is($deps[11]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[11]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[12]->module, 'Sub::Exporter', 'module is Sub::Exporter');
    is($deps[12]->depth, 3, 'depth is 3');
    is($deps[12]->warning, '', 'warning is empty');
    is($deps[12]->text_result, '', 'textresult is empty');
    is($deps[12]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[12]->total_results, 195, 'totalresults is 195');
    is($deps[12]->passes, 195, 'passes is 195');
    is($deps[12]->fails, 0, 'fails is 0');
    is($deps[12]->unknowns, 0, 'unknowns is 0');
    is($deps[12]->nas, 0, 'nas is 0');
    is($deps[12]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[12]->dependencies}, '==', 3, 'number of dependency modules');

    is($deps[13]->module, 'Params::Util', 'module is Params::Util');
    is($deps[13]->depth, 4, 'depth is 4');
    is($deps[13]->warning, '', 'warning is empty');
    is($deps[13]->text_result, '', 'textresult is empty');
    is($deps[13]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[13]->total_results, 179, 'totalresults is 179');
    is($deps[13]->passes, 179, 'passes is 179');
    is($deps[13]->fails, 0, 'fails is 0');
    is($deps[13]->unknowns, 0, 'unknowns is 0');
    is($deps[13]->nas, 0, 'nas is 0');
    is($deps[13]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[13]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[14]->module, 'Sub::Install', 'module is Sub::Install');
    is($deps[14]->depth, 4, 'depth is 4');
    is($deps[14]->warning, '', 'warning is empty');
    is($deps[14]->text_result, '', 'textresult is empty');
    is($deps[14]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[14]->total_results, 188, 'totalresults is 188');
    is($deps[14]->passes, 188, 'passes is 188');
    is($deps[14]->fails, 0, 'fails is 0');
    is($deps[14]->unknowns, 0, 'unknowns is 0');
    is($deps[14]->nas, 0, 'nas is 0');
    is($deps[14]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[14]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[15]->module, 'Data::OptList', 'module is Data::OptList');
    is($deps[15]->depth, 4, 'depth is 4');
    is($deps[15]->warning, '', 'warning is empty');
    is($deps[15]->text_result, '', 'textresult is empty');
    is($deps[15]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[15]->total_results, 189, 'totalresults is 189');
    is($deps[15]->passes, 189, 'passes is 189');
    is($deps[15]->fails, 0, 'fails is 0');
    is($deps[15]->unknowns, 0, 'unknowns is 0');
    is($deps[15]->nas, 0, 'nas is 0');
    is($deps[15]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[15]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[16]->module, 'Task::Weaken', 'module is Task::Weaken');
    is($deps[16]->depth, 2, 'depth is 2');
    is($deps[16]->warning, '', 'warning is empty');
    is($deps[16]->text_result, '', 'textresult is empty');
    is($deps[16]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[16]->total_results, 413, 'totalresults is 413');
    is($deps[16]->passes, 412, 'passes is 412');
    is($deps[16]->fails, 1, 'fails is 1');
    is($deps[16]->unknowns, 0, 'unknowns is 0');
    is($deps[16]->nas, 0, 'nas is 0');
    is($deps[16]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[16]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[17]->module, 'MRO::Compat', 'module is MRO::Compat');
    is($deps[17]->depth, 2, 'depth is 2');
    is($deps[17]->warning, '', 'warning is empty');
    is($deps[17]->text_result, '', 'textresult is empty');
    is($deps[17]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[17]->total_results, 122, 'totalresults is 122');
    is($deps[17]->passes, 122, 'passes is 122');
    is($deps[17]->fails, 0, 'fails is 0');
    is($deps[17]->unknowns, 0, 'unknowns is 0');
    is($deps[17]->nas, 0, 'nas is 0');
    is($deps[17]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[17]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[18]->module, 'Class::C3', 'module is Class::C3');
    is($deps[18]->depth, 3, 'depth is 3');
    is($deps[18]->warning, '', 'warning is empty');
    is($deps[18]->text_result, '', 'textresult is empty');
    is($deps[18]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[18]->total_results, 92, 'totalresults is 92');
    is($deps[18]->passes, 92, 'passes is 92');
    is($deps[18]->fails, 0, 'fails is 0');
    is($deps[18]->unknowns, 0, 'unknowns is 0');
    is($deps[18]->nas, 0, 'nas is 0');
    is($deps[18]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[18]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[19]->module, 'Algorithm::C3', 'module is Algorithm::C3');
    is($deps[19]->depth, 4, 'depth is 4');
    is($deps[19]->warning, '', 'warning is empty');
    is($deps[19]->text_result, '', 'textresult is empty');
    is($deps[19]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[19]->total_results, 59, 'totalresults is 59');
    is($deps[19]->passes, 59, 'passes is 59');
    is($deps[19]->fails, 0, 'fails is 0');
    is($deps[19]->unknowns, 0, 'unknowns is 0');
    is($deps[19]->nas, 0, 'nas is 0');
    is($deps[19]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[19]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[20]->module, 'MooseX::Emulate::Class::Accessor::Fast', 'module is MooseX::Emulate::Class::Accessor::Fast');
    is($deps[20]->depth, 1, 'depth is 1');
    is($deps[20]->warning, '', 'warning is empty');
    is($deps[20]->text_result, '', 'textresult is empty');
    is($deps[20]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[20]->total_results, 71, 'totalresults is 71');
    is($deps[20]->passes, 66, 'passes is 66');
    is($deps[20]->fails, 5, 'fails is 5');
    is($deps[20]->unknowns, 0, 'unknowns is 0');
    is($deps[20]->nas, 0, 'nas is 0');
    is($deps[20]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[20]->dependencies}, '==', 2, 'number of dependency modules');

    is($deps[21]->module, 'namespace::clean', 'module is namespace::clean');
    is($deps[21]->depth, 2, 'depth is 2');
    is($deps[21]->warning, '', 'warning is empty');
    is($deps[21]->text_result, '', 'textresult is empty');
    is($deps[21]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[21]->total_results, 141, 'totalresults is 141');
    is($deps[21]->passes, 141, 'passes is 141');
    is($deps[21]->fails, 0, 'fails is 0');
    is($deps[21]->unknowns, 0, 'unknowns is 0');
    is($deps[21]->nas, 0, 'nas is 0');
    is($deps[21]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[21]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[22]->module, 'B::Hooks::EndOfScope', 'module is B::Hooks::EndOfScope');
    is($deps[22]->depth, 3, 'depth is 3');
    is($deps[22]->warning, '', 'warning is empty');
    is($deps[22]->text_result, '', 'textresult is empty');
    is($deps[22]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[22]->total_results, 90, 'totalresults is 90');
    is($deps[22]->passes, 90, 'passes is 90');
    is($deps[22]->fails, 0, 'fails is 0');
    is($deps[22]->unknowns, 0, 'unknowns is 0');
    is($deps[22]->nas, 0, 'nas is 0');
    is($deps[22]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[22]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[23]->module, 'Variable::Magic', 'module is Variable::Magic');
    is($deps[23]->depth, 4, 'depth is 4');
    is($deps[23]->warning, '', 'warning is empty');
    is($deps[23]->text_result, '', 'textresult is empty');
    is($deps[23]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[23]->total_results, 60, 'totalresults is 60');
    is($deps[23]->passes, 59, 'passes is 59');
    is($deps[23]->fails, 1, 'fails is 1');
    is($deps[23]->unknowns, 0, 'unknowns is 0');
    is($deps[23]->nas, 0, 'nas is 0');
    is($deps[23]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[23]->dependencies}, '==', 2, 'number of dependency modules');

    is($deps[24]->module, 'XSLoader', 'module is XSLoader');
    is($deps[24]->depth, 5, 'depth is 5');
    is($deps[24]->warning, '', 'warning is empty');
    is($deps[24]->text_result, 'Core module', 'textresult is Core module');
    is($deps[24]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[24]->total_results, 0, 'totalresults is 0');
    is($deps[24]->passes, '', 'passes is empty');
    is($deps[24]->fails, '', 'fails is empty');
    is($deps[24]->unknowns, '', 'unknowns is empty');
    is($deps[24]->nas, '', 'nas is empty');
    is($deps[24]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[24]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[25]->module, 'Exporter', 'module is Exporter');
    is($deps[25]->depth, 5, 'depth is 5');
    is($deps[25]->warning, '', 'warning is empty');
    is($deps[25]->text_result, 'Core module', 'textresult is Core module');
    is($deps[25]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[25]->total_results, 0, 'totalresults is 0');
    is($deps[25]->passes, '', 'passes is empty');
    is($deps[25]->fails, '', 'fails is empty');
    is($deps[25]->unknowns, '', 'unknowns is empty');
    is($deps[25]->nas, '', 'nas is empty');
    is($deps[25]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[25]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[26]->module, 'Moose', 'module is Moose');
    is($deps[26]->depth, 2, 'depth is 2');
    is($deps[26]->warning, '', 'warning is empty');
    is($deps[26]->text_result, '', 'textresult is empty');
    is($deps[26]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[26]->total_results, 65, 'totalresults is 65');
    is($deps[26]->passes, 65, 'passes is 65');
    is($deps[26]->fails, 0, 'fails is 0');
    is($deps[26]->unknowns, 0, 'unknowns is 0');
    is($deps[26]->nas, 0, 'nas is 0');
    is($deps[26]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[26]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[27]->module, 'List::MoreUtils', 'module is List::MoreUtils');
    is($deps[27]->depth, 3, 'depth is 3');
    is($deps[27]->warning, '', 'warning is empty');
    is($deps[27]->text_result, '', 'textresult is empty');
    is($deps[27]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[27]->total_results, 341, 'totalresults is 341');
    is($deps[27]->passes, 314, 'passes is 314');
    is($deps[27]->fails, 25, 'fails is 25');
    is($deps[27]->unknowns, 2, 'unknowns is 2');
    is($deps[27]->nas, 0, 'nas is 0');
    is($deps[27]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[27]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[28]->module, 'Tree::Simple::Visitor::FindByPath', 'module is Tree::Simple::Visitor::FindByPath');
    is($deps[28]->depth, 1, 'depth is 1');
    is($deps[28]->warning, "Couldn't get dependencies", "warning is Couldn't get dependencies");
    is($deps[28]->text_result, '', 'textresult is empty');
    is($deps[28]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[28]->total_results, 316, 'totalresults is 316');
    is($deps[28]->passes, 314, 'passes is 314');
    is($deps[28]->fails, 1, 'fails is 1');
    is($deps[28]->unknowns, 1, 'unknowns is 1');
    is($deps[28]->nas, 0, 'nas is 0');
    is($deps[28]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[28]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[29]->module, 'HTTP::Headers', 'module is HTTP::Headers');
    is($deps[29]->depth, 1, 'depth is 1');
    is($deps[29]->warning, '', 'warning is empty');
    is($deps[29]->text_result, '', 'textresult is empty');
    is($deps[29]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[29]->total_results, 104, 'totalresults is 104');
    is($deps[29]->passes, 103, 'passes is 103');
    is($deps[29]->fails, 1, 'fails is 1');
    is($deps[29]->unknowns, 0, 'unknowns is 0');
    is($deps[29]->nas, 0, 'nas is 0');
    is($deps[29]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[29]->dependencies}, '==', 6, 'number of dependency modules');

    is($deps[30]->module, 'Compress::Zlib', 'module is Compress::Zlib');
    is($deps[30]->depth, 2, 'depth is 2');
    is($deps[30]->warning, '', 'warning is empty');
    is($deps[30]->text_result, 'Core module', 'textresult is Core module');
    is($deps[30]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[30]->total_results, 0, 'totalresults is 0');
    is($deps[30]->passes, '', 'passes is empty');
    is($deps[30]->fails, '', 'fails is empty');
    is($deps[30]->unknowns, '', 'unknowns is empty');
    is($deps[30]->nas, '', 'nas is empty');
    is($deps[30]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[30]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[31]->module, 'Net::FTP', 'module is Net::FTP');
    is($deps[31]->depth, 2, 'depth is 2');
    is($deps[31]->warning, '', 'warning is empty');
    is($deps[31]->text_result, 'Core module', 'textresult is Core module');
    is($deps[31]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[31]->total_results, 0, 'totalresults is 0');
    is($deps[31]->passes, '', 'passes is empty');
    is($deps[31]->fails, '', 'fails is empty');
    is($deps[31]->unknowns, '', 'unknowns is empty');
    is($deps[31]->nas, '', 'nas is empty');
    is($deps[31]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[31]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[32]->module, 'URI', 'module is URI');
    is($deps[32]->depth, 2, 'depth is 2');
    is($deps[32]->warning, '', 'warning is empty');
    is($deps[32]->text_result, '', 'textresult is empty');
    is($deps[32]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[32]->total_results, 278, 'totalresults is 278');
    is($deps[32]->passes, 260, 'passes is 260');
    is($deps[32]->fails, 18, 'fails is 18');
    is($deps[32]->unknowns, 0, 'unknowns is 0');
    is($deps[32]->nas, 0, 'nas is 0');
    is($deps[32]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[32]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[33]->module, 'MIME::Base64', 'module is MIME::Base64');
    is($deps[33]->depth, 3, 'depth is 3');
    is($deps[33]->warning, '', 'warning is empty');
    is($deps[33]->text_result, 'Core module', 'textresult is Core module');
    is($deps[33]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[33]->total_results, 0, 'totalresults is 0');
    is($deps[33]->passes, '', 'passes is empty');
    is($deps[33]->fails, '', 'fails is empty');
    is($deps[33]->unknowns, '', 'unknowns is empty');
    is($deps[33]->nas, '', 'nas is empty');
    is($deps[33]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[33]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[34]->module, 'HTML::Tagset', 'module is HTML::Tagset');
    is($deps[34]->depth, 2, 'depth is 2');
    is($deps[34]->warning, '', 'warning is empty');
    is($deps[34]->text_result, '', 'textresult is empty');
    is($deps[34]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[34]->total_results, 331, 'totalresults is 331');
    is($deps[34]->passes, 330, 'passes is 330');
    is($deps[34]->fails, 0, 'fails is 0');
    is($deps[34]->unknowns, 1, 'unknowns is 1');
    is($deps[34]->nas, 0, 'nas is 0');
    is($deps[34]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[34]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[35]->module, 'HTML::Parser', 'module is HTML::Parser');
    is($deps[35]->depth, 2, 'depth is 2');
    is($deps[35]->warning, '', 'warning is empty');
    is($deps[35]->text_result, '', 'textresult is empty');
    is($deps[35]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[35]->total_results, 196, 'totalresults is 196');
    is($deps[35]->passes, 195, 'passes is 195');
    is($deps[35]->fails, 1, 'fails is 1');
    is($deps[35]->unknowns, 0, 'unknowns is 0');
    is($deps[35]->nas, 0, 'nas is 0');
    is($deps[35]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[35]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[36]->module, 'Digest::MD5', 'module is Digest::MD5');
    is($deps[36]->depth, 2, 'depth is 2');
    is($deps[36]->warning, '', 'warning is empty');
    is($deps[36]->text_result, 'Core module', 'textresult is Core module');
    is($deps[36]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[36]->total_results, 0, 'totalresults is 0');
    is($deps[36]->passes, '', 'passes is empty');
    is($deps[36]->fails, '', 'fails is empty');
    is($deps[36]->unknowns, '', 'unknowns is empty');
    is($deps[36]->nas, '', 'nas is empty');
    is($deps[36]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[36]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[37]->module, 'Text::Balanced', 'module is Text::Balanced');
    is($deps[37]->depth, 1, 'depth is 1');
    is($deps[37]->warning, '', 'warning is empty');
    is($deps[37]->text_result, 'Core module', 'textresult is Core module');
    is($deps[37]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[37]->total_results, 0, 'totalresults is 0');
    is($deps[37]->passes, '', 'passes is empty');
    is($deps[37]->fails, '', 'fails is empty');
    is($deps[37]->unknowns, '', 'unknowns is empty');
    is($deps[37]->nas, '', 'nas is empty');
    is($deps[37]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[37]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[38]->module, 'Data::Dump', 'module is Data::Dump');
    is($deps[38]->depth, 1, 'depth is 1');
    is($deps[38]->warning, '', 'warning is empty');
    is($deps[38]->text_result, '', 'textresult is empty');
    is($deps[38]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[38]->total_results, 167, 'totalresults is 167');
    is($deps[38]->passes, 166, 'passes is 166');
    is($deps[38]->fails, 0, 'fails is 0');
    is($deps[38]->unknowns, 1, 'unknowns is 1');
    is($deps[38]->nas, 0, 'nas is 0');
    is($deps[38]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[38]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[39]->module, 'Class::Data::Inheritable', 'module is Class::Data::Inheritable');
    is($deps[39]->depth, 1, 'depth is 1');
    is($deps[39]->warning, '', 'warning is empty');
    is($deps[39]->text_result, '', 'textresult is empty');
    is($deps[39]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[39]->total_results, 403, 'totalresults is 403');
    is($deps[39]->passes, 403, 'passes is 403');
    is($deps[39]->fails, 0, 'fails is 0');
    is($deps[39]->unknowns, 0, 'unknowns is 0');
    is($deps[39]->nas, 0, 'nas is 0');
    is($deps[39]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[39]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[40]->module, 'File::Modified', 'module is File::Modified');
    is($deps[40]->depth, 1, 'depth is 1');
    is($deps[40]->warning, '', 'warning is empty');
    is($deps[40]->text_result, '', 'textresult is empty');
    is($deps[40]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[40]->total_results, 345, 'totalresults is 345');
    is($deps[40]->passes, 344, 'passes is 344');
    is($deps[40]->fails, 0, 'fails is 0');
    is($deps[40]->unknowns, 1, 'unknowns is 1');
    is($deps[40]->nas, 0, 'nas is 0');
    is($deps[40]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[40]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[41]->module, 'Test::MockObject', 'module is Test::MockObject');
    is($deps[41]->depth, 1, 'depth is 1');
    is($deps[41]->warning, '', 'warning is empty');
    is($deps[41]->text_result, '', 'textresult is empty');
    is($deps[41]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[41]->total_results, 293, 'totalresults is 293');
    is($deps[41]->passes, 264, 'passes is 264');
    is($deps[41]->fails, 0, 'fails is 0');
    is($deps[41]->unknowns, 0, 'unknowns is 0');
    is($deps[41]->nas, 29, 'nas is 29');
    is($deps[41]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[41]->dependencies}, '==', 2, 'number of dependency modules');

    is($deps[42]->module, 'UNIVERSAL::isa', 'module is UNIVERSAL::isa');
    is($deps[42]->depth, 2, 'depth is 2');
    is($deps[42]->warning, '', 'warning is empty');
    is($deps[42]->text_result, '', 'textresult is empty');
    is($deps[42]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[42]->total_results, 259, 'totalresults is 259');
    is($deps[42]->passes, 256, 'passes is 256');
    is($deps[42]->fails, 2, 'fails is 2');
    is($deps[42]->unknowns, 0, 'unknowns is 0');
    is($deps[42]->nas, 1, 'nas is 1');
    is($deps[42]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[42]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[43]->module, 'UNIVERSAL::can', 'module is UNIVERSAL::can');
    is($deps[43]->depth, 2, 'depth is 2');
    is($deps[43]->warning, '', 'warning is empty');
    is($deps[43]->text_result, '', 'textresult is empty');
    is($deps[43]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[43]->total_results, 358, 'totalresults is 358');
    is($deps[43]->passes, 357, 'passes is 357');
    is($deps[43]->fails, 0, 'fails is 0');
    is($deps[43]->unknowns, 0, 'unknowns is 0');
    is($deps[43]->nas, 1, 'nas is 1');
    is($deps[43]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[43]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[44]->module, 'MooseX::MethodAttributes::Inheritable', 'module is MooseX::MethodAttributes::Inheritable');
    is($deps[44]->depth, 1, 'depth is 1');
    is($deps[44]->warning, "Couldn't get dependencies", "warning is Couldn't get dependencies");
    is($deps[44]->text_result, '', 'textresult is empty');
    is($deps[44]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[44]->total_results, 47, 'totalresults is 47');
    is($deps[44]->passes, 47, 'passes is 47');
    is($deps[44]->fails, 0, 'fails is 0');
    is($deps[44]->unknowns, 0, 'unknowns is 0');
    is($deps[44]->nas, 0, 'nas is 0');
    is($deps[44]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[44]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[45]->module, 'HTTP::Request::AsCGI', 'module is HTTP::Request::AsCGI');
    is($deps[45]->depth, 1, 'depth is 1');
    is($deps[45]->warning, "Couldn't get dependencies", "warning is Couldn't get dependencies");
    is($deps[45]->text_result, '', 'textresult is empty');
    is($deps[45]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[45]->total_results, 68, 'totalresults is 68');
    is($deps[45]->passes, 68, 'passes is 68');
    is($deps[45]->fails, 0, 'fails is 0');
    is($deps[45]->unknowns, 0, 'unknowns is 0');
    is($deps[45]->nas, 0, 'nas is 0');
    is($deps[45]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[45]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[46]->module, 'Module::Pluggable', 'module is Module::Pluggable');
    is($deps[46]->depth, 1, 'depth is 1');
    is($deps[46]->warning, '', 'warning is empty');
    is($deps[46]->text_result, 'Core module', 'textresult is Core module');
    is($deps[46]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[46]->total_results, 0, 'totalresults is 0');
    is($deps[46]->passes, '', 'passes is empty');
    is($deps[46]->fails, '', 'fails is empty');
    is($deps[46]->unknowns, '', 'unknowns is empty');
    is($deps[46]->nas, '', 'nas is empty');
    is($deps[46]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[46]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[47]->module, 'Class::C3::Adopt::NEXT', 'module is Class::C3::Adopt::NEXT');
    is($deps[47]->depth, 1, 'depth is 1');
    is($deps[47]->warning, '', 'warning is empty');
    is($deps[47]->text_result, '', 'textresult is empty');
    is($deps[47]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[47]->total_results, 39, 'totalresults is 39');
    is($deps[47]->passes, 39, 'passes is 39');
    is($deps[47]->fails, 0, 'fails is 0');
    is($deps[47]->unknowns, 0, 'unknowns is 0');
    is($deps[47]->nas, 0, 'nas is 0');
    is($deps[47]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[47]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[48]->module, 'NEXT', 'module is NEXT');
    is($deps[48]->depth, 2, 'depth is 2');
    is($deps[48]->warning, '', 'warning is empty');
    is($deps[48]->text_result, 'Core module', 'textresult is Core module');
    is($deps[48]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[48]->total_results, 0, 'totalresults is 0');
    is($deps[48]->passes, '', 'passes is empty');
    is($deps[48]->fails, '', 'fails is empty');
    is($deps[48]->unknowns, '', 'unknowns is empty');
    is($deps[48]->nas, '', 'nas is empty');
    is($deps[48]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[48]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[49]->module, 'HTTP::Body', 'module is HTTP:Body');
    is($deps[49]->depth, 1, 'depth is 1');
    is($deps[49]->warning, '', 'warning is empty');
    is($deps[49]->text_result, '', 'textresult is empty');
    is($deps[49]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[49]->total_results, 190, 'totalresults is 190');
    is($deps[49]->passes, 189, 'passes is 189');
    is($deps[49]->fails, 1, 'fails is 1');
    is($deps[49]->unknowns, 0, 'unknowns is 0');
    is($deps[49]->nas, 0, 'nas is 0');
    is($deps[49]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[49]->dependencies}, '==', 3, 'number of dependency modules');

    is($deps[50]->module, 'IO::File', 'module is IO::File');
    is($deps[50]->depth, 2, 'depth is 2');
    is($deps[50]->warning, '', 'warning is empty');
    is($deps[50]->text_result, 'Core module', 'textresult is Core module');
    is($deps[50]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[50]->total_results, 0, 'totalresults is 0');
    is($deps[50]->passes, '', 'passes is empty');
    is($deps[50]->fails, '', 'fails is empty');
    is($deps[50]->unknowns, '', 'unknowns is empty');
    is($deps[50]->nas, '', 'nas is empty');
    is($deps[50]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[50]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[51]->module, 'YAML', 'module is YAML');
    is($deps[51]->depth, 2, 'depth is 2');
    is($deps[51]->warning, '', 'warning is empty');
    is($deps[51]->text_result, '', 'textresult is empty');
    is($deps[51]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[51]->total_results, 194, 'totalresults is 194');
    is($deps[51]->passes, 193, 'passes is 193');
    is($deps[51]->fails, 1, 'fails is 1');
    is($deps[51]->unknowns, 0, 'unknowns is 0');
    is($deps[51]->nas, 0, 'nas is 0');
    is($deps[51]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[51]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[52]->module, 'Filter::Util::Call', 'module is Filter::Util::Call');
    is($deps[52]->depth, 3, 'depth is 3');
    is($deps[52]->warning, '', 'warning is empty');
    is($deps[52]->text_result, 'Core module', 'textresult is Core module');
    is($deps[52]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[52]->total_results, 0, 'totalresults is 0');
    is($deps[52]->passes, '', 'passes is empty');
    is($deps[52]->fails, '', 'fails is empty');
    is($deps[52]->unknowns, '', 'unknowns is empty');
    is($deps[52]->nas, '', 'nas is empty');
    is($deps[52]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[52]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[53]->module, 'File::Temp', 'module is File::Temp');
    is($deps[53]->depth, 2, 'depth is 2');
    is($deps[53]->warning, '', 'warning is empty');
    is($deps[53]->text_result, 'Core module', 'textresult is Core module');
    is($deps[53]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[53]->total_results, 0, 'totalresults is 0');
    is($deps[53]->passes, '', 'passes is empty');
    is($deps[53]->fails, '', 'fails is empty');
    is($deps[53]->unknowns, '', 'unknowns is empty');
    is($deps[53]->nas, '', 'nas is empty');
    is($deps[53]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[53]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[54]->module, 'Text::SimpleTable', 'module is Text::SimpleTable');
    is($deps[54]->depth, 1, 'depth is 1');
    is($deps[54]->warning, '', 'warning is empty');
    is($deps[54]->text_result, '', 'textresult is empty');
    is($deps[54]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[54]->total_results, 252, 'totalresults is 252');
    is($deps[54]->passes, 246, 'passes is 246');
    is($deps[54]->fails, 6, 'fails is 6');
    is($deps[54]->unknowns, 0, 'unknowns is 0');
    is($deps[54]->nas, 0, 'nas is 0');
    is($deps[54]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[54]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[55]->module, 'Time::HiRes', 'module is Time::HiRes');
    is($deps[55]->depth, 1, 'depth is 1');
    is($deps[55]->warning, '', 'warning is empty');
    is($deps[55]->text_result, 'Core module', 'textresult is Core module');
    is($deps[55]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[55]->total_results, 0, 'totalresults is 0');
    is($deps[55]->passes, '', 'passes is empty');
    is($deps[55]->fails, '', 'fails is empty');
    is($deps[55]->unknowns, '', 'unknowns is empty');
    is($deps[55]->nas, '', 'nas is empty');
    is($deps[55]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[55]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[56]->module, 'CGI::Simple::Cookie', 'module is CGI::Simple::Cookie');
    is($deps[56]->depth, 1, 'depth is 1');
    is($deps[56]->warning, '', 'warning is empty');
    is($deps[56]->text_result, '', 'textresult is empty');
    is($deps[56]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[56]->total_results, 82, 'totalresults is 82');
    is($deps[56]->passes, 82, 'passes is 82');
    is($deps[56]->fails, 0, 'fails is 0');
    is($deps[56]->unknowns, 0, 'unknowns is 0');
    is($deps[56]->nas, 0, 'nas is 0');
    is($deps[56]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[56]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[57]->module, 'Path::Class', 'module is Path::Class');
    is($deps[57]->depth, 1, 'depth is 1');
    is($deps[57]->warning, '', 'warning is empty');
    is($deps[57]->text_result, '', 'textresult is empty');
    is($deps[57]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[57]->total_results, 359, 'totalresults is 359');
    is($deps[57]->passes, 358, 'passes is 358');
    is($deps[57]->fails, 1, 'fails is 1');
    is($deps[57]->unknowns, 0, 'unknowns is 0');
    is($deps[57]->nas, 0, 'nas is 0');
    is($deps[57]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[57]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[58]->module, 'File::Path', 'module is File::Path');
    is($deps[58]->depth, 2, 'depth is 2');
    is($deps[58]->warning, '', 'warning is empty');
    is($deps[58]->text_result, 'Core module', 'textresult is Core module');
    is($deps[58]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[58]->total_results, 0, 'totalresults is 0');
    is($deps[58]->passes, '', 'passes is empty');
    is($deps[58]->fails, '', 'fails is empty');
    is($deps[58]->unknowns, '', 'unknowns is empty');
    is($deps[58]->nas, '', 'nas is empty');
    is($deps[58]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[58]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[59]->module, 'Tree::Simple', 'module is Tree::Simple');
    is($deps[59]->depth, 1, 'depth is 1');
    is($deps[59]->warning, '', 'warning is empty');
    is($deps[59]->text_result, '', 'textresult is empty');
    is($deps[59]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[59]->total_results, 344, 'totalresults is 344');
    is($deps[59]->passes, 315, 'passes is 315');
    is($deps[59]->fails, 1, 'fails is 1');
    is($deps[59]->unknowns, 0, 'unknowns is 0');
    is($deps[59]->nas, 28, 'nas is 28');
    is($deps[59]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[59]->dependencies}, '==', 0, 'number of dependency modules');

}

{
    my ($module, $perl, $os) = ('Moose', '5.8.5', 'Linux');
    Test::WebService::CPANTesters::Dependency->set_module($module);

    diag("module: " . $module);

    my $dep = WebService::CPANTesters::Dependency->new(+{
        perl => $perl,
        os => $os
    });
    $dep->find($module);
    my @deps = $dep->list();

    cmp_ok(@deps, '==', 22, 'number of dependency modules');

    is($deps[0]->module, 'Scalar::Util', 'module is Scalar::Util');
    is($deps[0]->depth, 1, 'depth is 1');
    is($deps[0]->warning, '', 'warning is empty');
    is($deps[0]->text_result, '', 'textresult is empty');
    is($deps[0]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[0]->total_results, 0, 'totalresults is 0');
    is($deps[0]->passes, '', 'passes is empty');
    is($deps[0]->fails, '', 'fails is empty');
    is($deps[0]->unknowns, '', 'unknowns is empty');
    is($deps[0]->nas, '', 'nas is empty');
    is($deps[0]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[0]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[1]->module, 'Test::More', 'module is Test::More');
    is($deps[1]->depth, 2, 'depth is 2');
    is($deps[1]->warning, '', 'warning is empty');
    is($deps[1]->text_result, 'Core module', 'textresult is Core module');
    is($deps[1]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[1]->total_results, 0, 'totalresults is 0');
    is($deps[1]->passes, '', 'passes is empty');
    is($deps[1]->fails, '', 'fails is empty');
    is($deps[1]->unknowns, '', 'unknowns is empty');
    is($deps[1]->nas, '', 'nas is empty');
    is($deps[1]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[1]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[2]->module, 'Test::Exception', 'module is Test::Exception');
    is($deps[2]->depth, 1, 'depth is 1');
    is($deps[2]->warning, '', 'warning is empty');
    is($deps[2]->text_result, '', 'textresult is empty');
    is($deps[2]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[2]->total_results, 4, 'totalresults is 4');
    is($deps[2]->passes, 4, 'passes is 4');
    is($deps[2]->fails, 0, 'fails is 0');
    is($deps[2]->unknowns, 0, 'unknowns is 0');
    is($deps[2]->nas, 0, 'nas is 0');
    is($deps[2]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[2]->dependencies}, '==', 2, 'number of dependency modules');

    is($deps[3]->module, 'Test::Harness', 'module is Test::Harness');
    is($deps[3]->depth, 2, 'depth is 2');
    is($deps[3]->warning, '', 'warning is empty');
    is($deps[3]->text_result, 'Core module', 'textresult is Core module');
    is($deps[3]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[3]->total_results, 0, 'totalresults is 0');
    is($deps[3]->passes, '', 'passes is empty');
    is($deps[3]->fails, '', 'fails is empty');
    is($deps[3]->unknowns, '', 'unknowns is empty');
    is($deps[3]->nas, '', 'nas is empty');
    is($deps[3]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[3]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[4]->module, 'Sub::Uplevel', 'module is Sub::Uplevel');
    is($deps[4]->depth, 2, 'depth is 2');
    is($deps[4]->warning, '', 'warning is empty');
    is($deps[4]->text_result, '', 'textresult is empty');
    is($deps[4]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[4]->total_results, 10, 'totalresults is 10');
    is($deps[4]->passes, 10, 'passes is 10');
    is($deps[4]->fails, 0, 'fails is 0');
    is($deps[4]->unknowns, 0, 'unknowns is 0');
    is($deps[4]->nas, 0, 'nas is 0');
    is($deps[4]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[4]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[5]->module, 'Carp', 'module is Carp');
    is($deps[5]->depth, 3, 'depth is 3');
    is($deps[5]->warning, '', 'warning is empty');
    is($deps[5]->text_result, 'Core module', 'textresult is Core module');
    is($deps[5]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[5]->total_results, 0, 'totalresults is 0');
    is($deps[5]->passes, '', 'passes is empty');
    is($deps[5]->fails, '', 'fails is empty');
    is($deps[5]->unknowns, '', 'unknowns is empty');
    is($deps[5]->nas, '', 'nas is empty');
    is($deps[5]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[5]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[6]->module, 'Class::MOP', 'module is Class::MOP');
    is($deps[6]->depth, 1, 'depth is 1');
    is($deps[6]->warning, '', 'warning is empty');
    is($deps[6]->text_result, '', 'textresult is empty');
    is($deps[6]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[6]->total_results, 0, 'totalresults is 0');
    is($deps[6]->passes, '', 'passes is empty');
    is($deps[6]->fails, '', 'fails is empty');
    is($deps[6]->unknowns, '', 'unknowns is empty');
    is($deps[6]->nas, '', 'nas is empty');
    is($deps[6]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[6]->dependencies}, '==', 5, 'number of dependency modules');

    is($deps[7]->module, 'ExtUtils::MakeMaker', 'module is ExtUtils::MakeMaker');
    is($deps[7]->depth, 2, 'depth is 2');
    is($deps[7]->warning, '', 'warning is empty');
    is($deps[7]->text_result, '', 'textresult is empty');
    is($deps[7]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[7]->total_results, 10, 'totalresults is 10');
    is($deps[7]->passes, 10, 'passes is 10');
    is($deps[7]->fails, 0, 'fails is 0');
    is($deps[7]->unknowns, 0, 'unknowns is 0');
    is($deps[7]->nas, 0, 'nas is 0');
    is($deps[7]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[7]->dependencies}, '==', 2, 'number of dependency modules');

    is($deps[8]->module, 'File::Spec', 'module is File::Spec');
    is($deps[8]->depth, 3, 'depth is 3');
    is($deps[8]->warning, '', 'warning is empty');
    is($deps[8]->text_result, 'Core module', 'textresult is Core module');
    is($deps[8]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[8]->total_results, 0, 'totalresults is 0');
    is($deps[8]->passes, '', 'passes is empty');
    is($deps[8]->fails, '', 'fails is empty');
    is($deps[8]->unknowns, '', 'unknowns is empty');
    is($deps[8]->nas, '', 'nas is empty');
    is($deps[8]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[8]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[9]->module, 'Pod::Man', 'module is Pod::Man');
    is($deps[9]->depth, 3, 'depth is 3');
    is($deps[9]->warning, '', 'warning is empty');
    is($deps[9]->text_result, 'Core module', 'textresult is Core module');
    is($deps[9]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[9]->total_results, 0, 'totalresults is 0');
    is($deps[9]->passes, '', 'passes is empty');
    is($deps[9]->fails, '', 'fails is empty');
    is($deps[9]->unknowns, '', 'unknowns is empty');
    is($deps[9]->nas, '', 'nas is empty');
    is($deps[9]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[9]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[10]->module, 'Sub::Name', 'module is Sub::Name');
    is($deps[10]->depth, 2, 'depth is 2');
    is($deps[10]->warning, '', 'warning is empty');
    is($deps[10]->text_result, '', 'textresult is empty');
    is($deps[10]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[10]->total_results, 2, 'totalresults is 2');
    is($deps[10]->passes, 2, 'passes is 2');
    is($deps[10]->fails, 0, 'fails is 0');
    is($deps[10]->unknowns, 0, 'unknowns is 0');
    is($deps[10]->nas, 0, 'nas is 0');
    is($deps[10]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[10]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[11]->module, 'Devel::GlobalDestruction', 'module is Devel::Destruction');
    is($deps[11]->depth, 2, 'depth is 2');
    is($deps[11]->warning, '', 'warning is empty');
    is($deps[11]->text_result, '', 'textresult is empty');
    is($deps[11]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[11]->total_results, 2, 'totalresults is 2');
    is($deps[11]->passes, 2, 'passes is 2');
    is($deps[11]->fails, 0, 'fails is 0');
    is($deps[11]->unknowns, 0, 'unknowns is 0');
    is($deps[11]->nas, 0, 'nas is 0');
    is($deps[11]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[11]->dependencies}, '==', 2, 'number of dependency modules');

    is($deps[12]->module, 'Scope::Guard', 'module is Scope::Guard');
    is($deps[12]->depth, 3, 'depth is 3');
    is($deps[12]->warning, '', 'warning is empty');
    is($deps[12]->text_result, '', 'textresult is empty');
    is($deps[12]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[12]->total_results, 4, 'totalresults is 4');
    is($deps[12]->passes, 4, 'passes is 4');
    is($deps[12]->fails, 0, 'fails is 0');
    is($deps[12]->unknowns, 0, 'unknowns is 0');
    is($deps[12]->nas, 0, 'nas is 0');
    is($deps[12]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[12]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[13]->module, 'Sub::Exporter', 'module is Sub::Exporter');
    is($deps[13]->depth, 3, 'depth is 3');
    is($deps[13]->warning, '', 'warning is empty');
    is($deps[13]->text_result, '', 'textresult is empty');
    is($deps[13]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[13]->total_results, 1, 'totalresults is 1');
    is($deps[13]->passes, 1, 'passes is 1');
    is($deps[13]->fails, 0, 'fails is 0');
    is($deps[13]->unknowns, 0, 'unknowns is 0');
    is($deps[13]->nas, 0, 'nas is 0');
    is($deps[13]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[13]->dependencies}, '==', 3, 'number of dependency modules');

    is($deps[14]->module, 'Params::Util', 'module is Params::Util');
    is($deps[14]->depth, 4, 'depth is 4');
    is($deps[14]->warning, '', 'warning is empty');
    is($deps[14]->text_result, '', 'textresult is empty');
    is($deps[14]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[14]->total_results, 1, 'totalresults is 1');
    is($deps[14]->passes, 1, 'passes is 1');
    is($deps[14]->fails, 0, 'fails is 0');
    is($deps[14]->unknowns, 0, 'unknowns is 0');
    is($deps[14]->nas, 0, 'nas is 0');
    is($deps[14]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[14]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[15]->module, 'Sub::Install', 'module is Sub::Install');
    is($deps[15]->depth, 4, 'depth is 4');
    is($deps[15]->warning, '', 'warning is empty');
    is($deps[15]->text_result, '', 'textresult is empty');
    is($deps[15]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[15]->total_results, 1, 'totalresults is 1');
    is($deps[15]->passes, 1, 'passes is 1');
    is($deps[15]->fails, 0, 'fails is 0');
    is($deps[15]->unknowns, 0, 'unknowns is 0');
    is($deps[15]->nas, 0, 'nas is 0');
    is($deps[15]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[15]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[16]->module, 'Data::OptList', 'module is Data::OptList');
    is($deps[16]->depth, 4, 'depth is 4');
    is($deps[16]->warning, '', 'warning is empty');
    is($deps[16]->text_result, '', 'textresult is empty');
    is($deps[16]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[16]->total_results, 1, 'totalresults is 1');
    is($deps[16]->passes, 1, 'passes is 1');
    is($deps[16]->fails, 0, 'fails is 0');
    is($deps[16]->unknowns, 0, 'unknowns is 0');
    is($deps[16]->nas, 0, 'nas is 0');
    is($deps[16]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[16]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[17]->module, 'Task::Weaken', 'module is Task::Weaken');
    is($deps[17]->depth, 2, 'depth is 2');
    is($deps[17]->warning, '', 'warning is empty');
    is($deps[17]->text_result, '', 'textresult is empty');
    is($deps[17]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[17]->total_results, 6, 'totalresults is 6');
    is($deps[17]->passes, 6, 'passes is 6');
    is($deps[17]->fails, 0, 'fails is 0');
    is($deps[17]->unknowns, 0, 'unknowns is 0');
    is($deps[17]->nas, 0, 'nas is 0');
    is($deps[17]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[17]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[18]->module, 'MRO::Compat', 'module is MRO::Compat');
    is($deps[18]->depth, 2, 'depth is 2');
    is($deps[18]->warning, '', 'warning is empty');
    is($deps[18]->text_result, '', 'textresult is empty');
    is($deps[18]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[18]->total_results, 0, 'totalresults is 0');
    is($deps[18]->passes, '', 'passes is empty');
    is($deps[18]->fails, '', 'fails is empty');
    is($deps[18]->unknowns, '', 'unknowns is empty');
    is($deps[18]->nas, '', 'nas is empty');
    is($deps[18]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[18]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[19]->module, 'Class::C3', 'module is Class::C3');
    is($deps[19]->depth, 3, 'depth is 3');
    is($deps[19]->warning, '', 'warning is empty');
    is($deps[19]->text_result, '', 'textresult is empty');
    is($deps[19]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[19]->total_results, 0, 'totalresults is 0');
    is($deps[19]->passes, '', 'passes is empty');
    is($deps[19]->fails, '', 'fails is empty');
    is($deps[19]->unknowns, '', 'unknowns is empty');
    is($deps[19]->nas, '', 'nas is empty');
    is($deps[19]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[19]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[20]->module, 'Algorithm::C3', 'module is Algorithm::C3');
    is($deps[20]->depth, 4, 'depth is 4');
    is($deps[20]->warning, '', 'warning is empty');
    is($deps[20]->text_result, '', 'textresult is empty');
    is($deps[20]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[20]->total_results, 3, 'totalresults is 3');
    is($deps[20]->passes, 3, 'passes is 3');
    is($deps[20]->fails, 0, 'fails is 0');
    is($deps[20]->unknowns, 0, 'unknowns is 0');
    is($deps[20]->nas, 0, 'nas is 0');
    is($deps[20]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[20]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[21]->module, 'List::MoreUtils', 'module is List::MoreUtils');
    is($deps[21]->depth, 1, 'depth is 1');
    is($deps[21]->warning, '', 'warning is empty');
    is($deps[21]->text_result, '', 'textresult is empty');
    is($deps[21]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[21]->total_results, 4, 'totalresults is 4');
    is($deps[21]->passes, 4, 'passes is 4');
    is($deps[21]->fails, 0, 'fails is 0');
    is($deps[21]->unknowns, 0, 'unknowns is 0');
    is($deps[21]->nas, 0, 'nas is 0');
    is($deps[21]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[21]->dependencies}, '==', 0, 'number of dependency modules');

}

{
    my ($module, $perl, $os) = ('Apache2::ASP', '5.9.6', 'Mac OS X');
    Test::WebService::CPANTesters::Dependency->set_module($module);

    diag("module: " . $module);

    my $dep = WebService::CPANTesters::Dependency->new(+{
        perl => $perl,
        os => $os
    });
    $dep->find($module);
    my @deps = $dep->list(1);

    cmp_ok(@deps, '==', 64, 'number of dependency modules');

    is($deps[0]->module, 'Scalar::Util', 'module is Scalar::Util');
    is($deps[0]->depth, 5, 'depth is 5');
    is($deps[0]->warning, '', 'warning is empty');
    is($deps[0]->text_result, '', 'textresult is empty');
    is($deps[0]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[0]->total_results, 0, 'totalresults is 0');
    is($deps[0]->passes, '', 'passes is empty');
    is($deps[0]->fails, '', 'fails is empty');
    is($deps[0]->unknowns, '', 'unknowns is empty');
    is($deps[0]->nas, '', 'nas is empty');
    is($deps[0]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[0]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[1]->module, 'Carp', 'module is Carp');
    is($deps[1]->depth, 5, 'depth is 5');
    is($deps[1]->warning, '', 'warning is empty');
    is($deps[1]->text_result, 'Core module', 'textresult is Core module');
    is($deps[1]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[1]->total_results, 0, 'totalresults is 0');
    is($deps[1]->passes, '', 'passes is empty');
    is($deps[1]->fails, '', 'fails is empty');
    is($deps[1]->unknowns, '', 'unknowns is empty');
    is($deps[1]->nas, '', 'nas is empty');
    is($deps[1]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[1]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[2]->module, 'Test', 'module is Test');
    is($deps[2]->depth, 5, 'depth is 5');
    is($deps[2]->warning, '', 'warning is empty');
    is($deps[2]->text_result, '', 'textresult is empty');
    is($deps[2]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[2]->total_results, 0, 'totalresults is 0');
    is($deps[2]->passes, '', 'passes is empty');
    is($deps[2]->fails, '', 'fails is empty');
    is($deps[2]->unknowns, '', 'unknowns is empty');
    is($deps[2]->nas, '', 'nas is empty');
    is($deps[2]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[2]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[3]->module, 'File::Path', 'module is File::Path');
    is($deps[3]->depth, 5, 'depth is 5');
    is($deps[3]->warning, '', 'warning is empty');
    is($deps[3]->text_result, '', 'textresult is empty');
    is($deps[3]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[3]->total_results, 0, 'totalresults is 0');
    is($deps[3]->passes, '', 'passes is empty');
    is($deps[3]->fails, '', 'fails is empty');
    is($deps[3]->unknowns, '', 'unknowns is empty');
    is($deps[3]->nas, '', 'nas is empty');
    is($deps[3]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[3]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[4]->module, 'Pod::Escapes', 'module is Pod::Escapes');
    is($deps[4]->depth, 10, 'depth is 10');
    is($deps[4]->warning, '', 'warning is empty');
    is($deps[4]->text_result, '', 'textresult is empty');
    is($deps[4]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[4]->total_results, 0, 'totalresults is 0');
    is($deps[4]->passes, '', 'passes is empty');
    is($deps[4]->fails, '', 'fails is empty');
    is($deps[4]->unknowns, '', 'unknowns is empty');
    is($deps[4]->nas, '', 'nas is empty');
    is($deps[4]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[4]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[5]->module, 'constant', 'module is constant');
    is($deps[5]->depth, 10, 'depth is 10');
    is($deps[5]->warning, '', 'warning is empty');
    is($deps[5]->text_result, '', 'textresult is empty');
    is($deps[5]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[5]->total_results, 0, 'totalresults is 0');
    is($deps[5]->passes, '', 'passes is empty');
    is($deps[5]->fails, '', 'fails is empty');
    is($deps[5]->unknowns, '', 'unknowns is empty');
    is($deps[5]->nas, '', 'nas is empty');
    is($deps[5]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[5]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[6]->module, 'strict', 'module is strict');
    is($deps[6]->depth, 10, 'depth is 10');
    is($deps[6]->warning, '', 'warning is empty');
    is($deps[6]->text_result, 'Core module', 'textresult is Core module');
    is($deps[6]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[6]->total_results, 0, 'totalresults is 0');
    is($deps[6]->passes, '', 'passes is empty');
    is($deps[6]->fails, '', 'fails is empty');
    is($deps[6]->unknowns, '', 'unknowns is empty');
    is($deps[6]->nas, '', 'nas is empty');
    is($deps[6]->is_core, 1, 'this is core module');
    cmp_ok(@{$deps[6]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[7]->module, 'Text::Wrap', 'module is Text::Wrap');
    is($deps[7]->depth, 10, 'depth is 10');
    is($deps[7]->warning, '', 'warning is empty');
    is($deps[7]->text_result, '', 'textresult is empty');
    is($deps[7]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[7]->total_results, 0, 'totalresults is 0');
    is($deps[7]->passes, '', 'passes is empty');
    is($deps[7]->fails, '', 'fails is empty');
    is($deps[7]->unknowns, '', 'unknowns is empty');
    is($deps[7]->nas, '', 'nas is empty');
    is($deps[7]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[7]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[8]->module, 'Pod::Simple', 'module is Pod::Simple');
    is($deps[8]->depth, 9, 'depth is 9');
    is($deps[8]->warning, '', 'warning is empty');
    is($deps[8]->text_result, '', 'textresult is empty');
    is($deps[8]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[8]->total_results, 0, 'totalresults is 0');
    is($deps[8]->passes, '', 'passes is empty');
    is($deps[8]->fails, '', 'fails is empty');
    is($deps[8]->unknowns, '', 'unknowns is empty');
    is($deps[8]->nas, '', 'nas is empty');
    is($deps[8]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[8]->dependencies}, '==', 4, 'number of dependency modules');

    is($deps[9]->module, 'Pod::Man', 'module is Pod::Man');
    is($deps[9]->depth, 8, 'depth is 8');
    is($deps[9]->warning, '', 'warning is empty');
    is($deps[9]->text_result, '', 'textresult is empty');
    is($deps[9]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[9]->total_results, 0, 'totalresults is 0');
    is($deps[9]->passes, '', 'passes is empty');
    is($deps[9]->fails, '', 'fails is empty');
    is($deps[9]->unknowns, '', 'unknowns is empty');
    is($deps[9]->nas, '', 'nas is empty');
    is($deps[9]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[9]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[10]->module, 'ExtUtils::MakeMaker', 'module is ExtUtils::MakeMaker');
    is($deps[10]->depth, 7, 'depth is 7');
    is($deps[10]->warning, '', 'warning is empty');
    is($deps[10]->text_result, '', 'textresult is empty');
    is($deps[10]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[10]->total_results, 0, 'totalresults is 0');
    is($deps[10]->passes, '', 'passes is empty');
    is($deps[10]->fails, '', 'fails is empty');
    is($deps[10]->unknowns, '', 'unknowns is empty');
    is($deps[10]->nas, '', 'nas is empty');
    is($deps[10]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[10]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[11]->module, 'ExtUtils::Install', 'module is ExtUtils::Install');
    is($deps[11]->depth, 6, 'depth is 6');
    is($deps[11]->warning, '', 'warning is empty');
    is($deps[11]->text_result, '', 'textresult is empty');
    is($deps[11]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[11]->total_results, 0, 'totalresults is 0');
    is($deps[11]->passes, '', 'passes is empty');
    is($deps[11]->fails, '', 'fails is empty');
    is($deps[11]->unknowns, '', 'unknowns is empty');
    is($deps[11]->nas, '', 'nas is empty');
    is($deps[11]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[11]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[12]->module, 'Compress::Raw::Bzip2', 'module is Compress::Raw::Bzip2');
    is($deps[12]->depth, 8, 'depth is 8');
    is($deps[12]->warning, '', 'warning is empty');
    is($deps[12]->text_result, '', 'textresult is empty');
    is($deps[12]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[12]->total_results, 0, 'totalresults is 0');
    is($deps[12]->passes, '', 'passes is empty');
    is($deps[12]->fails, '', 'fails is empty');
    is($deps[12]->unknowns, '', 'unknowns is empty');
    is($deps[12]->nas, '', 'nas is empty');
    is($deps[12]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[12]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[13]->module, 'Compress::Raw::Zlib', 'module is Compress::Raw::Zlib');
    is($deps[13]->depth, 8, 'depth is 8');
    is($deps[13]->warning, '', 'warning is empty');
    is($deps[13]->text_result, '', 'textresult is empty');
    is($deps[13]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[13]->total_results, 0, 'totalresults is 0');
    is($deps[13]->passes, '', 'passes is empty');
    is($deps[13]->fails, '', 'fails is empty');
    is($deps[13]->unknowns, '', 'unknowns is empty');
    is($deps[13]->nas, '', 'nas is empty');
    is($deps[13]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[13]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[14]->module, 'Compress::Zlib', 'module is Compress::Zlib');
    is($deps[14]->depth, 7, 'depth is 7');
    is($deps[14]->warning, '', 'warning is empty');
    is($deps[14]->text_result, '', 'textresult is empty');
    is($deps[14]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[14]->total_results, 0, 'totalresults is 0');
    is($deps[14]->passes, '', 'passes is empty');
    is($deps[14]->fails, '', 'fails is empty');
    is($deps[14]->unknowns, '', 'unknowns is empty');
    is($deps[14]->nas, '', 'nas is empty');
    is($deps[14]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[14]->dependencies}, '==', 2, 'number of dependency modules');

    is($deps[15]->module, 'IO::Zlib', 'module is IO::Zlib');
    is($deps[15]->depth, 7, 'depth is 7');
    is($deps[15]->warning, '', 'warning is empty');
    is($deps[15]->text_result, '', 'textresult is empty');
    is($deps[15]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[15]->total_results, 0, 'totalresults is 0');
    is($deps[15]->passes, '', 'passes is empty');
    is($deps[15]->fails, '', 'fails is empty');
    is($deps[15]->unknowns, '', 'unknowns is empty');
    is($deps[15]->nas, '', 'nas is empty');
    is($deps[15]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[15]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[16]->module, 'Package::Constants', 'module is Package::Constants');
    is($deps[16]->depth, 7, 'depth is 7');
    is($deps[16]->warning, '', 'warning is empty');
    is($deps[16]->text_result, '', 'textresult is empty');
    is($deps[16]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[16]->total_results, 0, 'totalresults is 0');
    is($deps[16]->passes, '', 'passes is empty');
    is($deps[16]->fails, '', 'fails is empty');
    is($deps[16]->unknowns, '', 'unknowns is empty');
    is($deps[16]->nas, '', 'nas is empty');
    is($deps[16]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[16]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[17]->module, 'Archive::Tar', 'module is Archive::Tar');
    is($deps[17]->depth, 6, 'depth is 6');
    is($deps[17]->warning, '', 'warning is empty');
    is($deps[17]->text_result, '', 'textresult is empty');
    is($deps[17]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[17]->total_results, 0, 'totalresults is 0');
    is($deps[17]->passes, '', 'passes is empty');
    is($deps[17]->fails, '', 'fails is empty');
    is($deps[17]->unknowns, '', 'unknowns is empty');
    is($deps[17]->nas, '', 'nas is empty');
    is($deps[17]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[17]->dependencies}, '==', 3, 'number of dependency modules');

    is($deps[18]->module, 'ExtUtils::Manifest', 'module is ExtUtils::Manifest');
    is($deps[18]->depth, 6, 'depth is 6');
    is($deps[18]->warning, '', 'warning is empty');
    is($deps[18]->text_result, '', 'textresult is empty');
    is($deps[18]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[18]->total_results, 0, 'totalresults is 0');
    is($deps[18]->passes, '', 'passes is empty');
    is($deps[18]->fails, '', 'fails is empty');
    is($deps[18]->unknowns, '', 'unknowns is empty');
    is($deps[18]->nas, '', 'nas is empty');
    is($deps[18]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[18]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[19]->module, 'Pod::Usage', 'module is Pod::Usage');
    is($deps[19]->depth, 7, 'depth is 7');
    is($deps[19]->warning, '', 'warning is empty');
    is($deps[19]->text_result, '', 'textresult is empty');
    is($deps[19]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[19]->total_results, 0, 'totalresults is 0');
    is($deps[19]->passes, '', 'passes is empty');
    is($deps[19]->fails, '', 'fails is empty');
    is($deps[19]->unknowns, '', 'unknowns is empty');
    is($deps[19]->nas, '', 'nas is empty');
    is($deps[19]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[19]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[20]->module, 'Getopt::Long', 'module is Getopt::Long');
    is($deps[20]->depth, 6, 'depth is 6');
    is($deps[20]->warning, '', 'warning is empty');
    is($deps[20]->text_result, '', 'textresult is empty');
    is($deps[20]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[20]->total_results, 0, 'totalresults is 0');
    is($deps[20]->passes, '', 'passes is empty');
    is($deps[20]->fails, '', 'fails is empty');
    is($deps[20]->unknowns, '', 'unknowns is empty');
    is($deps[20]->nas, '', 'nas is empty');
    is($deps[20]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[20]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[21]->module, 'IO::File', 'module is IO::File');
    is($deps[21]->depth, 6, 'depth is 6');
    is($deps[21]->warning, '', 'warning is empty');
    is($deps[21]->text_result, '', 'textresult is empty');
    is($deps[21]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[21]->total_results, 0, 'totalresults is 0');
    is($deps[21]->passes, '', 'passes is empty');
    is($deps[21]->fails, '', 'fails is empty');
    is($deps[21]->unknowns, '', 'unknowns is empty');
    is($deps[21]->nas, '', 'nas is empty');
    is($deps[21]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[21]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[22]->module, 'Data::Dumper', 'module is Data::Dumper');
    is($deps[22]->depth, 6, 'depth is 6');
    is($deps[22]->warning, "Couldn't get dependencies", "warning is Couldn't get dependencies");
    is($deps[22]->text_result, '', 'textresult is empty');
    is($deps[22]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[22]->total_results, 0, 'totalresults is 0');
    is($deps[22]->passes, '', 'passes is empty');
    is($deps[22]->fails, '', 'fails is empty');
    is($deps[22]->unknowns, '', 'unknowns is empty');
    is($deps[22]->nas, '', 'nas is empty');
    is($deps[22]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[22]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[23]->module, 'Text::ParseWords', 'module is Text::ParseWords');
    is($deps[23]->depth, 6, 'depth is 6');
    is($deps[23]->warning, '', 'warning is empty');
    is($deps[23]->text_result, '', 'textresult is empty');
    is($deps[23]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[23]->total_results, 0, 'totalresults is 0');
    is($deps[23]->passes, '', 'passes is empty');
    is($deps[23]->fails, '', 'fails is empty');
    is($deps[23]->unknowns, '', 'unknowns is empty');
    is($deps[23]->nas, '', 'nas is empty');
    is($deps[23]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[23]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[24]->module, 'File::Temp', 'module is File::Temp');
    is($deps[24]->depth, 6, 'depth is 6');
    is($deps[24]->warning, '', 'warning is empty');
    is($deps[24]->text_result, '', 'textresult is empty');
    is($deps[24]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[24]->total_results, 0, 'totalresults is 0');
    is($deps[24]->passes, '', 'passes is empty');
    is($deps[24]->fails, '', 'fails is empty');
    is($deps[24]->unknowns, '', 'unknowns is empty');
    is($deps[24]->nas, '', 'nas is empty');
    is($deps[24]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[24]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[25]->module, 'Module::Build', 'module is Module::Build');
    is($deps[25]->depth, 5, 'depth is 5');
    is($deps[25]->warning, '', 'warning is empty');
    is($deps[25]->text_result, '', 'textresult is empty');
    is($deps[25]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[25]->total_results, 0, 'totalresults is 0');
    is($deps[25]->passes, '', 'passes is empty');
    is($deps[25]->fails, '', 'fails is empty');
    is($deps[25]->unknowns, '', 'unknowns is empty');
    is($deps[25]->nas, '', 'nas is empty');
    is($deps[25]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[25]->dependencies}, '==', 8, 'number of dependency modules');

    is($deps[26]->module, 'ExtUtils::CBuilder', 'module is ExtUtils::CBuilder');
    is($deps[26]->depth, 5, 'depth is 5');
    is($deps[26]->warning, '', 'warning is empty');
    is($deps[26]->text_result, '', 'textresult is empty');
    is($deps[26]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[26]->total_results, 0, 'totalresults is 0');
    is($deps[26]->passes, '', 'passes is empty');
    is($deps[26]->fails, '', 'fails is empty');
    is($deps[26]->unknowns, '', 'unknowns is empty');
    is($deps[26]->nas, '', 'nas is empty');
    is($deps[26]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[26]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[27]->module, 'File::Spec', 'module is File::Spec');
    is($deps[27]->depth, 4, 'depth is 4');
    is($deps[27]->warning, '', 'warning is empty');
    is($deps[27]->text_result, '', 'textresult is empty');
    is($deps[27]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[27]->total_results, 0, 'totalresults is 0');
    is($deps[27]->passes, '', 'passes is empty');
    is($deps[27]->fails, '', 'fails is empty');
    is($deps[27]->unknowns, '', 'unknowns is empty');
    is($deps[27]->nas, '', 'nas is empty');
    is($deps[27]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[27]->dependencies}, '==', 6, 'number of dependency modules');

    is($deps[28]->module, 'Test::Harness', 'module is Test::Harness');
    is($deps[28]->depth, 3, 'depth is 3');
    is($deps[28]->warning, '', 'warning is empty');
    is($deps[28]->text_result, '', 'textresult is empty');
    is($deps[28]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[28]->total_results, 0, 'totalresults is 0');
    is($deps[28]->passes, '', 'passes is empty');
    is($deps[28]->fails, '', 'fails is empty');
    is($deps[28]->unknowns, '', 'unknowns is empty');
    is($deps[28]->nas, '', 'nas is empty');
    is($deps[28]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[28]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[29]->module, 'Test::More', 'module is Test::More');
    is($deps[29]->depth, 2, 'depth is 2');
    is($deps[29]->warning, '', 'warning is empty');
    is($deps[29]->text_result, '', 'textresult is empty');
    is($deps[29]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[29]->total_results, 0, 'totalresults is 0');
    is($deps[29]->passes, '', 'passes is empty');
    is($deps[29]->fails, '', 'fails is empty');
    is($deps[29]->unknowns, '', 'unknowns is empty');
    is($deps[29]->nas, '', 'nas is empty');
    is($deps[29]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[29]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[30]->module, 'Storable', 'module is Storable');
    is($deps[30]->depth, 3, 'depth is 3');
    is($deps[30]->warning, '', 'warning is empty');
    is($deps[30]->text_result, '', 'textresult is empty');
    is($deps[30]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[30]->total_results, 0, 'totalresults is 0');
    is($deps[30]->passes, '', 'passes is empty');
    is($deps[30]->fails, '', 'fails is empty');
    is($deps[30]->unknowns, '', 'unknowns is empty');
    is($deps[30]->nas, '', 'nas is empty');
    is($deps[30]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[30]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[31]->module, 'DBI', 'module is DBI');
    is($deps[31]->depth, 2, 'depth is 2');
    is($deps[31]->warning, '', 'warning is empty');
    is($deps[31]->text_result, '', 'textresult is empty');
    is($deps[31]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[31]->total_results, 0, 'totalresults is 0');
    is($deps[31]->passes, '', 'passes is empty');
    is($deps[31]->fails, '', 'fails is empty');
    is($deps[31]->unknowns, '', 'unknowns is empty');
    is($deps[31]->nas, '', 'nas is empty');
    is($deps[31]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[31]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[32]->module, 'DBD::SQLite', 'module is DBD::SQLite');
    is($deps[32]->depth, 1, 'depth is 1');
    is($deps[32]->warning, '', 'warning is empty');
    is($deps[32]->text_result, '', 'textresult is empty');
    is($deps[32]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[32]->total_results, 0, 'totalresults is 0');
    is($deps[32]->passes, '', 'passes is empty');
    is($deps[32]->fails, '', 'fails is empty');
    is($deps[32]->unknowns, '', 'unknowns is empty');
    is($deps[32]->nas, '', 'nas is empty');
    is($deps[32]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[32]->dependencies}, '==', 2, 'number of dependency modules');

    is($deps[33]->module, 'XML::NamespaceSupport', 'module is XML::NamespaceSupport');
    is($deps[33]->depth, 3, 'depth is 3');
    is($deps[33]->warning, '', 'warning is empty');
    is($deps[33]->text_result, '', 'textresult is empty');
    is($deps[33]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[33]->total_results, 0, 'totalresults is 0');
    is($deps[33]->passes, '', 'passes is empty');
    is($deps[33]->fails, '', 'fails is empty');
    is($deps[33]->unknowns, '', 'unknowns is empty');
    is($deps[33]->nas, '', 'nas is empty');
    is($deps[33]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[33]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[34]->module, 'XML::SAX', 'module is XML::SAX');
    is($deps[34]->depth, 2, 'depth is 2');
    is($deps[34]->warning, '', 'warning is empty');
    is($deps[34]->text_result, '', 'textresult is empty');
    is($deps[34]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[34]->total_results, 0, 'totalresults is 0');
    is($deps[34]->passes, '', 'passes is empty');
    is($deps[34]->fails, '', 'fails is empty');
    is($deps[34]->unknowns, '', 'unknowns is empty');
    is($deps[34]->nas, '', 'nas is empty');
    is($deps[34]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[34]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[35]->module, 'XML::Simple', 'module is XML::Simple');
    is($deps[35]->depth, 1, 'depth is 1');
    is($deps[35]->warning, '', 'warning is empty');
    is($deps[35]->text_result, '', 'textresult is empty');
    is($deps[35]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[35]->total_results, 0, 'totalresults is 0');
    is($deps[35]->passes, '', 'passes is empty');
    is($deps[35]->fails, '', 'fails is empty');
    is($deps[35]->unknowns, '', 'unknowns is empty');
    is($deps[35]->nas, '', 'nas is empty');
    is($deps[35]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[35]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[36]->module, 'PadWalker', 'module is PadWalker');
    is($deps[36]->depth, 2, 'depth is 2');
    is($deps[36]->warning, '', 'warning is empty');
    is($deps[36]->text_result, '', 'textresult is empty');
    is($deps[36]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[36]->total_results, 0, 'totalresults is 0');
    is($deps[36]->passes, '', 'passes is empty');
    is($deps[36]->fails, '', 'fails is empty');
    is($deps[36]->unknowns, '', 'unknowns is empty');
    is($deps[36]->nas, '', 'nas is empty');
    is($deps[36]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[36]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[37]->module, 'Devel::Cycle', 'module is Devel::Cycle');
    is($deps[37]->depth, 2, 'depth is 2');
    is($deps[37]->warning, '', 'warning is empty');
    is($deps[37]->text_result, '', 'textresult is empty');
    is($deps[37]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[37]->total_results, 0, 'totalresults is 0');
    is($deps[37]->passes, '', 'passes is empty');
    is($deps[37]->fails, '', 'fails is empty');
    is($deps[37]->unknowns, '', 'unknowns is empty');
    is($deps[37]->nas, '', 'nas is empty');
    is($deps[37]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[37]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[38]->module, 'Test::Memory::Cycle', 'module is Test::Memory::Cycle');
    is($deps[38]->depth, 1, 'depth is 1');
    is($deps[38]->warning, '', 'warning is empty');
    is($deps[38]->text_result, '', 'textresult is empty');
    is($deps[38]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[38]->total_results, 0, 'totalresults is 0');
    is($deps[38]->passes, '', 'passes is empty');
    is($deps[38]->fails, '', 'fails is empty');
    is($deps[38]->unknowns, '', 'unknowns is empty');
    is($deps[38]->nas, '', 'nas is empty');
    is($deps[38]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[38]->dependencies}, '==', 2, 'number of dependency modules');

    is($deps[39]->module, 'XSLoader', 'module is XSLoader');
    is($deps[39]->depth, 2, 'depth is 2');
    is($deps[39]->warning, '', 'warning is empty');
    is($deps[39]->text_result, '', 'textresult is empty');
    is($deps[39]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[39]->total_results, 0, 'totalresults is 0');
    is($deps[39]->passes, '', 'passes is empty');
    is($deps[39]->fails, '', 'fails is empty');
    is($deps[39]->unknowns, '', 'unknowns is empty');
    is($deps[39]->nas, '', 'nas is empty');
    is($deps[39]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[39]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[40]->module, 'Digest::base', 'module is Digest::base');
    is($deps[40]->depth, 2, 'depth is 2');
    is($deps[40]->warning, "Couldn't get dependencies", "warning is Couldn't get dependencies");
    is($deps[40]->text_result, '', 'textresult is empty');
    is($deps[40]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[40]->total_results, 0, 'totalresults is 0');
    is($deps[40]->passes, '', 'passes is empty');
    is($deps[40]->fails, '', 'fails is empty');
    is($deps[40]->unknowns, '', 'unknowns is empty');
    is($deps[40]->nas, '', 'nas is empty');
    is($deps[40]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[40]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[41]->module, 'Digest::MD5', 'module is Digest::MD5');
    is($deps[41]->depth, 1, 'depth is 1');
    is($deps[41]->warning, '', 'warning is empty');
    is($deps[41]->text_result, '', 'textresult is empty');
    is($deps[41]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[41]->total_results, 0, 'totalresults is 0');
    is($deps[41]->passes, '', 'passes is empty');
    is($deps[41]->fails, '', 'fails is empty');
    is($deps[41]->unknowns, '', 'unknowns is empty');
    is($deps[41]->nas, '', 'nas is empty');
    is($deps[41]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[41]->dependencies}, '==', 2, 'number of dependency modules');

    is($deps[42]->module, 'Apache2::RequestRec', 'module is Apache2::RequestRec');
    is($deps[42]->depth, 2, 'depth is 2');
    is($deps[42]->warning, '', 'warning is empty');
    is($deps[42]->text_result, '', 'textresult is empty');
    is($deps[42]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[42]->total_results, 0, 'totalresults is 0');
    is($deps[42]->passes, '', 'passes is empty');
    is($deps[42]->fails, '', 'fails is empty');
    is($deps[42]->unknowns, '', 'unknowns is empty');
    is($deps[42]->nas, '', 'nas is empty');
    is($deps[42]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[42]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[43]->module, 'CGI::Apache2::Wrapper', 'module is CGI::Apache2::Wrrapper');
    is($deps[43]->depth, 1, 'depth is 1');
    is($deps[43]->warning, '', 'warning is empty');
    is($deps[43]->text_result, '', 'textresult is empty');
    is($deps[43]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[43]->total_results, 0, 'totalresults is 0');
    is($deps[43]->passes, '', 'passes is empty');
    is($deps[43]->fails, '', 'fails is empty');
    is($deps[43]->unknowns, '', 'unknowns is empty');
    is($deps[43]->nas, '', 'nas is empty');
    is($deps[43]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[43]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[44]->module, 'Net::FTP', 'module is Net::FTP');
    is($deps[44]->depth, 3, 'depth is 3');
    is($deps[44]->warning, '', 'warning is empty');
    is($deps[44]->text_result, '', 'textresult is empty');
    is($deps[44]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[44]->total_results, 0, 'totalresults is 0');
    is($deps[44]->passes, '', 'passes is empty');
    is($deps[44]->fails, '', 'fails is empty');
    is($deps[44]->unknowns, '', 'unknowns is empty');
    is($deps[44]->nas, '', 'nas is empty');
    is($deps[44]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[44]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[45]->module, 'MIME::Base64', 'module is MIME::Base64');
    is($deps[45]->depth, 4, 'depth is 4');
    is($deps[45]->warning, "Couldn't get dependencies", "warning is Couldn't get dependencies");
    is($deps[45]->text_result, '', 'textresult is empty');
    is($deps[45]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[45]->total_results, 0, 'totalresults is 0');
    is($deps[45]->passes, '', 'passes is empty');
    is($deps[45]->fails, '', 'fails is empty');
    is($deps[45]->unknowns, '', 'unknowns is empty');
    is($deps[45]->nas, '', 'nas is empty');
    is($deps[45]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[45]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[46]->module, 'URI', 'module is URI');
    is($deps[46]->depth, 3, 'depth is 3');
    is($deps[46]->warning, '', 'warning is empty');
    is($deps[46]->text_result, '', 'textresult is empty');
    is($deps[46]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[46]->total_results, 0, 'totalresults is 0');
    is($deps[46]->passes, '', 'passes is empty');
    is($deps[46]->fails, '', 'fails is empty');
    is($deps[46]->unknowns, '', 'unknowns is empty');
    is($deps[46]->nas, '', 'nas is empty');
    is($deps[46]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[46]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[47]->module, 'HTML::Tagset', 'module is HTML::Tagset');
    is($deps[47]->depth, 4, 'depth is 4');
    is($deps[47]->warning, '', 'warning is empty');
    is($deps[47]->text_result, '', 'textresult is empty');
    is($deps[47]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[47]->total_results, 0, 'totalresults is 0');
    is($deps[47]->passes, '', 'passes is empty');
    is($deps[47]->fails, '', 'fails is empty');
    is($deps[47]->unknowns, '', 'unknowns is empty');
    is($deps[47]->nas, '', 'nas is empty');
    is($deps[47]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[47]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[48]->module, 'HTML::Parser', 'module is HTML::Parser');
    is($deps[48]->depth, 3, 'depth is 3');
    is($deps[48]->warning, '', 'warning is empty');
    is($deps[48]->text_result, '', 'textresult is empty');
    is($deps[48]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[48]->total_results, 0, 'totalresults is 0');
    is($deps[48]->passes, '', 'passes is empty');
    is($deps[48]->fails, '', 'fails is empty');
    is($deps[48]->unknowns, '', 'unknowns is empty');
    is($deps[48]->nas, '', 'nas is empty');
    is($deps[48]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[48]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[49]->module, 'LWP', 'module is LWP');
    is($deps[49]->depth, 2, 'depth is 2');
    is($deps[49]->warning, '', 'warning is empty');
    is($deps[49]->text_result, '', 'textresult is empty');
    is($deps[49]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[49]->total_results, 0, 'totalresults is 0');
    is($deps[49]->passes, '', 'passes is empty');
    is($deps[49]->fails, '', 'fails is empty');
    is($deps[49]->unknowns, '', 'unknowns is empty');
    is($deps[49]->nas, '', 'nas is empty');
    is($deps[49]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[49]->dependencies}, '==', 3, 'number of dependency modules');

    is($deps[50]->module, 'XML::Parser', 'module is XML::Parser');
    is($deps[50]->depth, 1, 'depth is 1');
    is($deps[50]->warning, '', 'warning is empty');
    is($deps[50]->text_result, '', 'textresult is empty');
    is($deps[50]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[50]->total_results, 0, 'totalresults is 0');
    is($deps[50]->passes, '', 'passes is empty');
    is($deps[50]->fails, '', 'fails is empty');
    is($deps[50]->unknowns, '', 'unknowns is empty');
    is($deps[50]->nas, '', 'nas is empty');
    is($deps[50]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[50]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[51]->module, 'CGI::Simple', 'module is CGI::Simple');
    is($deps[51]->depth, 1, 'depth is 1');
    is($deps[51]->warning, '', 'warning is empty');
    is($deps[51]->text_result, '', 'textresult is empty');
    is($deps[51]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[51]->total_results, 0, 'totalresults is 0');
    is($deps[51]->passes, '', 'passes is empty');
    is($deps[51]->fails, '', 'fails is empty');
    is($deps[51]->unknowns, '', 'unknowns is empty');
    is($deps[51]->nas, '', 'nas is empty');
    is($deps[51]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[51]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[52]->module, 'HTTP::Request::AsCGI', 'module is HTTP::Request::AsCGI');
    is($deps[52]->depth, 1, 'depth is 1');
    is($deps[52]->warning, "Couldn't get dependencies", "warning is Couldn't get dependencies");
    is($deps[52]->text_result, '', 'textresult is empty');
    is($deps[52]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[52]->total_results, 0, 'totalresults is 0');
    is($deps[52]->passes, '', 'passes is empty');
    is($deps[52]->fails, '', 'fails is empty');
    is($deps[52]->unknowns, '', 'unknowns is empty');
    is($deps[52]->nas, '', 'nas is empty');
    is($deps[52]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[52]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[53]->module, 'Filter::Util::Call', 'module is Filter::Util::Call');
    is($deps[53]->depth, 3, 'depth is 3');
    is($deps[53]->warning, '', 'warning is empty');
    is($deps[53]->text_result, '', 'textresult is empty');
    is($deps[53]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[53]->total_results, 0, 'totalresults is 0');
    is($deps[53]->passes, '', 'passes is empty');
    is($deps[53]->fails, '', 'fails is empty');
    is($deps[53]->unknowns, '', 'unknowns is empty');
    is($deps[53]->nas, '', 'nas is empty');
    is($deps[53]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[53]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[54]->module, 'YAML', 'module is YAML');
    is($deps[54]->depth, 2, 'depth is 2');
    is($deps[54]->warning, '', 'warning is empty');
    is($deps[54]->text_result, '', 'textresult is empty');
    is($deps[54]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[54]->total_results, 0, 'totalresults is 0');
    is($deps[54]->passes, '', 'passes is empty');
    is($deps[54]->fails, '', 'fails is empty');
    is($deps[54]->unknowns, '', 'unknowns is empty');
    is($deps[54]->nas, '', 'nas is empty');
    is($deps[54]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[54]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[55]->module, 'HTTP::Body', 'module is HTTP::Body');
    is($deps[55]->depth, 1, 'depth is 1');
    is($deps[55]->warning, '', 'warning is empty');
    is($deps[55]->text_result, '', 'textresult is empty');
    is($deps[55]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[55]->total_results, 0, 'totalresults is 0');
    is($deps[55]->passes, '', 'passes is empty');
    is($deps[55]->fails, '', 'fails is empty');
    is($deps[55]->unknowns, '', 'unknowns is empty');
    is($deps[55]->nas, '', 'nas is empty');
    is($deps[55]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[55]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[56]->module, 'Time::HiRes', 'module is Time::HiRes');
    is($deps[56]->depth, 1, 'depth is 1');
    is($deps[56]->warning, '', 'warning is empty');
    is($deps[56]->text_result, '', 'textresult is empty');
    is($deps[56]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[56]->total_results, 0, 'totalresults is 0');
    is($deps[56]->passes, '', 'passes is empty');
    is($deps[56]->fails, '', 'fails is empty');
    is($deps[56]->unknowns, '', 'unknowns is empty');
    is($deps[56]->nas, '', 'nas is empty');
    is($deps[56]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[56]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[57]->module, 'Test::Pod', 'module is Test::Pod');
    is($deps[57]->depth, 2, 'depth is 2');
    is($deps[57]->warning, '', 'warning is empty');
    is($deps[57]->text_result, '', 'textresult is empty');
    is($deps[57]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[57]->total_results, 0, 'totalresults is 0');
    is($deps[57]->passes, '', 'passes is empty');
    is($deps[57]->fails, '', 'fails is empty');
    is($deps[57]->unknowns, '', 'unknowns is empty');
    is($deps[57]->nas, '', 'nas is empty');
    is($deps[57]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[57]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[58]->module, 'MIME::Types', 'module is MIME::Types');
    is($deps[58]->depth, 1, 'depth is 1');
    is($deps[58]->warning, '', 'warning is empty');
    is($deps[58]->text_result, '', 'textresult is empty');
    is($deps[58]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[58]->total_results, 0, 'totalresults is 0');
    is($deps[58]->passes, '', 'passes is empty');
    is($deps[58]->fails, '', 'fails is empty');
    is($deps[58]->unknowns, '', 'unknowns is empty');
    is($deps[58]->nas, '', 'nas is empty');
    is($deps[58]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[58]->dependencies}, '==', 1, 'number of dependency modules');

    is($deps[59]->module, 'Mail::Sendmail', 'module is Mail::Sendmail');
    is($deps[59]->depth, 1, 'depth is 1');
    is($deps[59]->warning, "Couldn't get dependencies", "warning is Couldn't get dependencies");
    is($deps[59]->text_result, '', 'textresult is empty');
    is($deps[59]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[59]->total_results, 0, 'totalresults is 0');
    is($deps[59]->passes, '', 'passes is empty');
    is($deps[59]->fails, '', 'fails is empty');
    is($deps[59]->unknowns, '', 'unknowns is empty');
    is($deps[59]->nas, '', 'nas is empty');
    is($deps[59]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[59]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[60]->module, 'Class::Data::Inheritable', 'module is Class::Data::Inheritable');
    is($deps[60]->depth, 2, 'depth is 2');
    is($deps[60]->warning, '', 'warning is empty');
    is($deps[60]->text_result, '', 'textresult is empty');
    is($deps[60]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[60]->total_results, 0, 'totalresults is 0');
    is($deps[60]->passes, '', 'passes is empty');
    is($deps[60]->fails, '', 'fails is empty');
    is($deps[60]->unknowns, '', 'unknowns is empty');
    is($deps[60]->nas, '', 'nas is empty');
    is($deps[60]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[60]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[61]->module, 'DBIx::ContextualFetch', 'module is DBIx::ContextualFetch');
    is($deps[61]->depth, 2, 'depth is 2');
    is($deps[61]->warning, '', 'warning is empty');
    is($deps[61]->text_result, '', 'textresult is empty');
    is($deps[61]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[61]->total_results, 0, 'totalresults is 0');
    is($deps[61]->passes, '', 'passes is empty');
    is($deps[61]->fails, '', 'fails is empty');
    is($deps[61]->unknowns, '', 'unknowns is empty');
    is($deps[61]->nas, '', 'nas is empty');
    is($deps[61]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[61]->dependencies}, '==', 0, 'number of dependency modules');

    is($deps[62]->module, 'Ima::DBI', 'module is Ima::DBI');
    is($deps[62]->depth, 1, 'depth is 1');
    is($deps[62]->warning, '', 'warning is empty');
    is($deps[62]->text_result, '', 'textresult is empty');
    is($deps[62]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[62]->total_results, 0, 'totalresults is 0');
    is($deps[62]->passes, '', 'passes is empty');
    is($deps[62]->fails, '', 'fails is empty');
    is($deps[62]->unknowns, '', 'unknowns is empty');
    is($deps[62]->nas, '', 'nas is empty');
    is($deps[62]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[62]->dependencies}, '==', 2, 'number of dependency modules');

    is($deps[63]->module, 'Data::Properties::YAML', 'module is Data::Properties::YAML');
    is($deps[63]->depth, 1, 'depth is 1');
    is($deps[63]->warning, '', 'warning is empty');
    is($deps[63]->text_result, '', 'textresult is empty');
    is($deps[63]->is_pure_perl, '?', 'ispureperl is ?');
    is($deps[63]->total_results, 0, 'totalresults is 0');
    is($deps[63]->passes, '', 'passes is empty');
    is($deps[63]->fails, '', 'fails is empty');
    is($deps[63]->unknowns, '', 'unknowns is empty');
    is($deps[63]->nas, '', 'nas is empty');
    is($deps[63]->is_core, 0, 'this is not core module');
    cmp_ok(@{$deps[63]->dependencies}, '==', 0, 'number of dependency modules');

}

